# Generated by Django 5.0.6 on 2024-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('full_name', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('grade', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1000)),
            ],
        ),
    ]
