# Generated by Django 5.0.6 on 2024-07-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('full_name', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
                ('grade', models.CharField(max_length=1000)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
