# Generated by Django 5.0.6 on 2024-07-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_grad_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grad',
            new_name='Student',
        ),
    ]
